set -l git_diff '__git_diff'
set -l git_current_branch '__git_current_branch'

alias ga 'git add'
alias gb 'git branch'
alias gba 'git branch --all'
alias gcb 'git checkout -b'
alias gcm 'git checkout master'
alias gcmsg 'git commit -m'
alias gd "$git_diff"
alias gdca "$git_diff --cached"
alias gdf 'git diff'
alias gf 'git fetch'
alias gfa 'git fetch --all --prune'
alias ggpush "git push origin $git_current_branch"
alias glgga 'git log --graph --decorate --all'
alias gm 'git merge'
alias gp 'git push'
alias gr 'git remote'
alias gra 'git remote add'
alias grup 'git remote update'
alias grbi 'git rebase -i'
alias gsb 'git status -sb'
alias gst 'git status'
alias gsta 'git stash'
alias gstp 'git stash pop'
alias gup 'git pull --rebase'
